{{- if not .Values.auth.jwtSecretExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theoria.fullname" . }}-secrets
  labels:
    {{- include "theoria.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecret: {{ required "auth.jwtSecret is required when jwtSecretExistingSecret is unset" .Values.auth.jwtSecret | b64enc | quote }}
  {{- if .Values.auth.adminPassword }}
  adminPassword: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- end }}
{{- end -}}
